# Applying function on columns

In [1]:

import pandas as pd

In [2]:
df = pd.read_csv("data/imdb_1000.csv")

In [3]:
df.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [4]:
capitalize = lambda x: x.upper()

In [11]:
df['Title'] = df['Title'].apply(capitalize)

In [12]:
df['Title']

0                      GUARDIANS OF THE GALAXY
1                                   PROMETHEUS
2                                        SPLIT
3                                         SING
4                                SUICIDE SQUAD
5                               THE GREAT WALL
6                                   LA LA LAND
7                                     MINDHORN
8                           THE LOST CITY OF Z
9                                   PASSENGERS
10     FANTASTIC BEASTS AND WHERE TO FIND THEM
11                              HIDDEN FIGURES
12                                   ROGUE ONE
13                                       MOANA
14                                    COLOSSAL
15                     THE SECRET LIFE OF PETS
16                               HACKSAW RIDGE
17                                JASON BOURNE
18                                        LION
19                                     ARRIVAL
20                                        GOLD
21                       MANCHESTER BY THE SEA
22                              HOUNDS OF LOVE
23                                      TROLLS
24                INDEPENDENCE DAY: RESURGENCE
25                             PARIS PIEDS NUS
26                     BAHUBALI: THE BEGINNING
27                                  DEAD AWAKE
28                                    BAD MOMS
29                            ASSASSIN'S CREED
                        ...
970                          TEXAS CHAINSAW 3D
971                                  DISTURBIA
972                               ROCK OF AGES
973                                   SCREAM 4
974                             QUEEN OF KATWE
975                 MY BIG FAT GREEK WEDDING 2
976                                DARK PLACES
977                              AMATEUR NIGHT
978             IT'S ONLY THE END OF THE WORLD
979                         THE SKIN I LIVE IN
980                       MIRACLES FROM HEAVEN
981                                      ANNIE
982                        ACROSS THE UNIVERSE
983                              LET'S BE COPS
984                                        MAX
985                              YOUR HIGHNESS
986                        FINAL DESTINATION 5
987                               ENDLESS LOVE
988                                    MARTYRS
989                                      SELMA
990             UNDERWORLD: RISE OF THE LYCANS
991                           TAARE ZAMEEN PAR
992                       TAKE ME HOME TONIGHT
993                   RESIDENT EVIL: AFTERLIFE
994                                  PROJECT X
995                       SECRET IN THEIR EYES
996                            HOSTEL: PART II
997                     STEP UP 2: THE STREETS
998                               SEARCH PARTY
999                                 NINE LIVES
Name: Title, Length: 1000, dtype: object

In [13]:
df.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore,title
0,1,GUARDIANS OF THE GALAXY,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0,GUARDIANS OF THE GALAXY
1,2,PROMETHEUS,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0,PROMETHEUS
2,3,SPLIT,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0,SPLIT
3,4,SING,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0,SING
4,5,SUICIDE SQUAD,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0,SUICIDE SQUAD