# Group By

Any groupby operation involves one of the following operations on the original object. They are −

Splitting the Object

Applying a function

Combining the results

In many situations, we split the data into sets and we apply some functionality on each subset. In the apply functionality, we can perform the following operations −

Aggregation − computing a summary statistic

Transformation − perform some group-specific operation

Filtration − discarding the data with some condition

In [1]:
import pandas as pd

In [2]:
imdb_df = pd.read_csv("data/imdb_1000.csv")

In [3]:
imdb_df.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [4]:
genre_groups = imdb_df.groupby('Genre')

In [5]:
genre_groups

In [7]:
genre_groups.get_group('Horror,Thriller')

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
27,28,Dead Awake,"Horror,Thriller",A young woman must save herself and her friend...,Phillip Guzman,"Jocelin Donahue, Jesse Bradford, Jesse Borrego...",2016,99,4.7,523,0.01,NaN
116,117,The Neon Demon,"Horror,Thriller",When aspiring model Jesse moves to Los Angeles...,Nicolas Winding Refn,"Elle Fanning, Christina Hendricks, Keanu Reeve...",2016,118,6.2,50359,1.33,51.0
361,362,Clown,"Horror,Thriller",A loving father finds a clown suit for his son...,Jon Watts,"Andy Powers, Laura Allen, Peter Stormare, Chri...",2014,100,5.7,14248,0.05,42.0
382,383,Hush,"Horror,Thriller",A deaf writer who retreated into the woods to ...,Mike Flanagan,"John Gallagher Jr., Kate Siegel, Michael Trucc...",2016,81,6.6,45867,NaN,67.0
477,478,Pet,"Horror,Thriller",A psychological thriller about a man who bumps...,Carles Torrens,"Dominic Monaghan, Ksenia Solo, Jennette McCurd...",2016,94,5.7,8404,NaN,48.0
531,532,Friend Request,"Horror,Thriller",When a college student unfriends a mysterious ...,Simon Verhoeven,"Alycia Debnam-Carey, William Moseley, Connor P...",2016,92,5.4,12758,64.03,59.0
723,724,Blair Witch,"Horror,Thriller",After discovering a video showing what he beli...,Adam Wingard,"James Allen McCune, Callie Hernandez, Corbin R...",2016,89,5.1,26088,20.75,47.0
736,737,The Blackcoat's Daughter,"Horror,Thriller",Two girls must battle a mysterious evil force ...,Oz Perkins,"Emma Roberts, Kiernan Shipka, Lauren Holly, Lu...",2015,93,5.6,4155,0.02,68.0
748,749,Ouija: Origin of Evil,"Horror,Thriller","In 1967 Los Angeles, a widowed mother and her ...",Mike Flanagan,"Elizabeth Reaser, Lulu Wilson, Annalise Basso,...",2016,99,6.1,30035,34.90,65.0
776,777,31,"Horror,Thriller",Five carnival workers are kidnapped and held h...,Rob Zombie,"Malcolm McDowell, Richard Brake, Jeff Daniel P...",2016,102,5.1,10871,0.78,35.0
811,812,Mama,"Horror,Thriller",A young couple take in their two nieces only t...,Andrés Muschietti,"Jessica Chastain, Nikolaj Coster-Waldau, Megan...",2013,100,6.2,142560,71.59,57.0
819,820,Wolves at the Door,"Horror,Thriller",Four friends gather at an elegant home during ...,John R. Leonetti,"Katie Cassidy, Elizabeth Henstridge, Adam Camp...",2016,73,4.6,564,NaN,63.0
825,826,Crawlspace,"Horror,Thriller",A thriller centered around a widower who moves...,Phil Claydon,"Michael Vartan, Erin Moriarty, Nadine Velazque...",2016,88,5.3,1427,NaN,25.0
970,971,Texas Chainsaw 3D,"Horror,Thriller",A young woman travels to Texas to collect an i...,John Luessenhop,"Alexandra Daddario, Tania Raymonde, Scott East...",2013,92,4.8,37060,34.33,62.0
986,987,Final Destination 5,"Horror,Thriller",Survivors of a suspension-bridge collapse lear...,Steven Quale,"Nicholas D'Agosto, Emma Bell, Arlen Escarpeta,...",2011,92,5.9,88000,42.58,50.0

In [8]:
genre_groups.aggregate('mean').sort_values('Rating')

,Rank,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Genre,,,,,,,
"Fantasy,Horror,Thriller",648.000000,2016.000000,133.000000,3.200000,1.730000e+02,NaN,57.000000
"Comedy,Western",643.000000,2015.000000,119.000000,4.800000,3.114900e+04,NaN,18.000000
Sci-Fi,400.500000,2016.000000,106.500000,4.950000,7.265000e+02,20.760000,53.000000
"Sci-Fi,Thriller",513.000000,2008.000000,91.000000,5.000000,1.708970e+05,64.510000,34.000000
"Action,Fantasy,Thriller",586.000000,2007.000000,114.000000,5.200000,1.906730e+05,115.800000,35.000000
"Drama,Horror,Thriller",384.666667,2015.000000,92.833333,5.233333,2.879583e+04,16.110000,60.800000
"Action,Horror",318.000000,2016.000000,81.000000,5.300000,1.263000e+03,NaN,NaN
"Action,Crime,Sport",494.000000,2015.000000,114.000000,5.300000,4.455300e+04,28.770000,34.000000
"Comedy,Family,Fantasy",1000.000000,2016.000000,87.000000,5.300000,1.243500e+04,19.640000,11.000000
"Adventure,Horror",350.500000,2014.500000,92.000000,5.300000,1.429400e+04,7.190000,48.500000
"Horror,Sci-Fi,Thriller",396.333333,2015.000000,93.000000,5.433333,5.969233e+04,34.165000,41.333333
Horror,578.090909,2011.090909,94.545455,5.445455,9.224618e+04,37.052857,57.000000
"Action,Adventure,Family",443.750000,2013.750000,105.500000,5.575000,1.371575e+05,112.866667,39.500000
"Drama,Fantasy,Mystery",774.000000,2006.000000,110.000000,5.600000,8.270100e+04,42.270000,36.000000
"Adventure,Comedy,Fantasy",986.000000,2011.000000,102.000000,5.600000,8.790400e+04,21.560000,31.000000
"Action,Comedy,Family",387.000000,2015.000000,105.000000,5.600000,1.010920e+05,78.750000,27.000000
"Horror,Thriller",581.625000,2015.125000,95.562500,5.643750,3.940781e+04,34.040833,53.400000
"Comedy,Horror",642.000000,2012.500000,111.000000,5.650000,5.064300e+04,8.210000,64.500000
"Action,Horror,Sci-Fi",361.000000,2011.800000,98.200000,5.740000,1.251892e+05,54.004000,45.250000
"Horror,Mystery,Sci-Fi",98.000000,2016.000000,90.000000,5.800000,9.247000e+03,0.150000,62.000000
"Action,Horror,Romance",423.000000,2016.000000,108.000000,5.800000,3.500300e+04,10.910000,45.000000
"Action,Horror,Thriller",636.333333,2012.666667,121.000000,5.800000,5.509067e+04,17.595000,40.500000
"Action,Fantasy,Horror",754.333333,2011.666667,106.000000,5.833333,1.078760e+05,44.553333,34.666667
"Action,Adventure,Romance",293.000000,2012.000000,117.500000,5.850000,9.459050e+04,23.470000,35.000000
"Adventure,Comedy",704.500000,2014.500000,96.000000,5.850000,3.973500e+04,58.880000,28.000000
"Comedy,Horror,Thriller",604.000000,2012.500000,91.000000,5.850000,7.834550e+04,45.035000,54.000000
"Comedy,Drama,Musical",973.000000,2012.000000,123.000000,5.900000,6.451300e+04,38.510000,47.000000
Thriller,681.444444,2014.777778,95.222222,5.955556,3.396022e+04,0.320000,59.714286
"Drama,Romance,Thriller",369.000000,2014.333333,115.333333,5.966667,1.197710e+05,118.750000,37.666667
"Comedy,Family,Romance",976.000000,2016.000000,94.000000,6.000000,2.096600e+04,59.570000,37.000000
...,...,...,...,...,...,...,...
"Adventure,Drama,Thriller",273.666667,2012.333333,139.666667,7.566667,3.134970e+05,82.743333,63.000000
"Animation,Fantasy",712.000000,2016.000000,80.000000,7.600000,1.148200e+04,0.920000,86.000000
"Action,Drama,War",241.000000,2014.000000,134.000000,7.600000,3.322340e+05,85.710000,64.000000
"Crime,Mystery,Thriller",192.500000,2014.500000,110.500000,7.600000,2.497640e+05,117.700000,50.000000
"Adventure,Drama,Western",744.000000,2010.000000,110.000000,7.600000,2.549040e+05,171.030000,80.000000
"Drama,Musical,Romance",246.000000,2012.000000,158.000000,7.600000,2.574260e+05,148.780000,63.000000
"Comedy,Fantasy,Romance",350.000000,2011.000000,94.000000,7.700000,3.203230e+05,56.820000,81.000000
"Adventure,Comedy,Horror",364.000000,2009.000000,88.000000,7.700000,4.094030e+05,75.590000,73.000000
"Animation,Family,Fantasy",443.000000,2009.000000,100.000000,7.700000,1.566200e+05,75.280000,80.000000
"Action,Fantasy,War",114.000000,2006.000000,117.000000,7.700000,6.371040e+05,210.590000,52.000000
"Drama,Mystery,Sci-Fi",300.666667,2012.500000,110.000000,7.716667,3.522362e+05,37.548000,72.833333
"Biography,Drama,Thriller",396.000000,2014.333333,127.333333,7.733333,3.194540e+05,73.233333,71.333333
"Adventure,Fantasy",368.333333,2013.000000,158.000000,7.733333,5.226643e+05,272.156667,61.000000
"Biography,Drama,Mystery",860.000000,2008.000000,141.000000,7.800000,2.067930e+05,35.710000,63.000000
"Drama,Music",582.333333,2011.333333,108.333333,7.800000,2.267933e+05,20.306667,62.666667
"Animation,Comedy,Drama",794.000000,2016.000000,66.000000,7.800000,4.370000e+03,0.290000,85.000000
"Crime,Drama,History",235.500000,2011.000000,142.500000,7.900000,2.989825e+05,39.020000,85.500000
"Action,Comedy,Mystery",160.000000,2007.000000,121.000000,7.900000,3.732440e+05,23.620000,81.000000
"Drama,Family",696.000000,2009.000000,93.000000,8.100000,1.776020e+05,NaN,61.000000
"Comedy,Drama,Thriller",642.000000,2014.000000,122.000000,8.100000,1.101000e+05,3.080000,77.000000
"Animation,Adventure,Family",403.500000,2012.000000,99.500000,8.150000,4.248375e+05,135.915000,84.000000
"Drama,Mystery,War",714.000000,2010.000000,131.000000,8.200000,9.286300e+04,6.860000,80.000000
"Drama,Fantasy,War",231.000000,2006.000000,118.000000,8.200000,4.988790e+05,37.620000,98.000000
"Biography,Comedy,Crime",83.000000,2013.000000,180.000000,8.200000,8.651340e+05,116.870000,75.000000
"Adventure,Drama,War",78.000000,2009.000000,153.000000,8.300000,9.590650e+05,120.520000,69.000000
"Adventure,Drama,Sci-Fi",70.000000,2014.500000,156.500000,8.300000,8.019220e+05,208.210000,77.000000
"Animation,Drama,Romance",862.000000,2016.000000,129.000000,8.400000,2.421000e+03,NaN,80.000000
"Drama,Western",145.000000,2012.000000,165.000000,8.400000,1.039115e+06,162.800000,81.000000
"Drama,Family,Music",992.000000,2007.000000,165.000000,8.500000,1.026970e+05,1.200000,42.000000
"Animation,Drama,Fantasy",97.000000,2016.000000,106.000000,8.600000,3.411000e+04,4.680000,79.000000

In [9]:
import numpy as np

In [10]:
genre_groups['Runtime (Minutes)'].aggregate([np.max, np.min, np.mean, np.std])

                            amax  amin        mean        std
Genre
Action                        90    86   88.000000   2.828427
Action,Adventure             139    98  124.333333  22.854613
Action,Adventure,Biography   141   122  131.500000  13.435029
Action,Adventure,Comedy      129    83  109.642857  12.469083
Action,Adventure,Crime       129    98  116.500000  12.533954
Action,Adventure,Drama       159    97  124.166667  15.964114
Action,Adventure,Family      130    92  105.500000  16.941074
Action,Adventure,Fantasy     169    85  118.148148  20.635488
Action,Adventure,Horror      116    97  106.500000  13.435029
Action,Adventure,Mystery     146   118  128.600000  11.738824
Action,Adventure,Romance     125   110  117.500000  10.606602
Action,Adventure,Sci-Fi      165    88  127.360000  16.680381
Action,Adventure,Thriller    148   103  126.363636  16.181920
Action,Adventure,Western     150   132  141.000000  12.727922
Action,Biography,Crime        92    92   92.000000        NaN
Action,Biography,Drama       161   103  125.875000  18.247798
Action,Comedy                117    98  106.666667   7.339391
Action,Comedy,Crime          119    90  108.166667   8.653253
Action,Comedy,Drama          109   109  109.000000        NaN
Action,Comedy,Family         105   105  105.000000        NaN
Action,Comedy,Fantasy        116   104  110.666667   6.110101
Action,Comedy,Horror         105    93   99.000000   8.485281
Action,Comedy,Mystery        121   121  121.000000        NaN
Action,Comedy,Romance        103    95   99.000000   5.656854
Action,Comedy,Sci-Fi         109   109  109.000000        NaN
Action,Comedy,Sport          108   108  108.000000        NaN
Action,Crime,Drama           152    88  113.117647  16.646630
Action,Crime,Fantasy         110   110  110.000000        NaN
Action,Crime,Mystery         130   100  115.000000  15.000000
Action,Crime,Sci-Fi          117   117  117.000000        NaN
...                          ...   ...         ...        ...
Drama,Romance,Sci-Fi         126    97  107.500000  12.871156
Drama,Romance,Thriller       125   106  115.333333   9.504385
Drama,Romance,War            107   107  107.000000        NaN
Drama,Sci-Fi                 172    96  134.000000  53.740115
Drama,Sci-Fi,Thriller        109    91  101.250000   7.588368
Drama,Sport                  133    88  112.800000  17.908099
Drama,Thriller               138    90  114.466667  15.546551
Drama,Thriller,War           102   102  102.000000        NaN
Drama,War                    113    94  106.666667  10.969655
Drama,Western                165   165  165.000000        NaN
Fantasy,Horror               104    91   97.500000   9.192388
Fantasy,Horror,Thriller      133   133  133.000000        NaN
Fantasy,Mystery,Thriller      99    99   99.000000        NaN
Horror                       126    73   94.545455  13.887863
Horror,Mystery               111    92  102.500000   7.314369
Horror,Mystery,Sci-Fi         90    90   90.000000        NaN
Horror,Mystery,Thriller      134    86  104.888889  15.972198
Horror,Sci-Fi,Thriller       102    85   93.000000   8.544004
Horror,Thriller              118    73   95.562500  11.360568
Mystery,Romance,Sci-Fi        93    93   93.000000        NaN
Mystery,Romance,Thriller     108   108  108.000000        NaN
Mystery,Sci-Fi,Thriller      112    89  102.000000  11.789826
Mystery,Thriller             149    91  116.142857  22.711440
Mystery,Thriller,Western     148   148  148.000000        NaN
Romance,Sci-Fi               118   118  118.000000        NaN
Romance,Sci-Fi,Thriller      106   106  106.000000        NaN
Sci-Fi                       112   101  106.500000   7.778175
Sci-Fi,Thriller               91    91   91.000000        NaN
Thriller                     113    81   95.222222  10.951915
Thriller,War                 106   106  106.000000        NaN

[207 rows x 4 columns]

In [12]:
imdb_df['avg_duration'] = genre_groups['Runtime (Minutes)'].transform(lambda x: x.mean())

In [13]:
imdb_df.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore,avg_duration
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0,127.360000
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0,131.500000
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0,95.562500
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0,104.600000
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0,118.148148

In [15]:
imdb_df['Genre'].value_counts()

Action,Adventure,Sci-Fi       50
Drama                         48
Comedy,Drama,Romance          35
Comedy                        32
Drama,Romance                 31
Animation,Adventure,Comedy    27
Action,Adventure,Fantasy      27
Comedy,Drama                  27
Comedy,Romance                26
Crime,Drama,Thriller          24
Crime,Drama,Mystery           23
Action,Adventure,Drama        18
Action,Crime,Drama            17
Horror,Thriller               16
Drama,Thriller                15
Adventure,Family,Fantasy      14
Action,Adventure,Comedy       14
Biography,Drama               14
Biography,Drama,History       14
Action,Comedy,Crime           12
Action,Crime,Thriller         12
Action,Adventure,Thriller     11
Horror                        11
Crime,Drama                   10
Animation,Action,Adventure     9
Horror,Mystery,Thriller        9
Biography,Crime,Drama          9
Thriller                       9
Action,Thriller                9
Adventure,Comedy,Drama         8
                              ..
Comedy,Drama,Thriller          1
Comedy,Sci-Fi                  1
Action,Comedy,Mystery          1
Adventure,Drama,History        1
Comedy,Romance,Sport           1
Action,Comedy,Sport            1
Biography,History,Thriller     1
Crime,Thriller                 1
Action,Drama,War               1
Animation,Action,Comedy        1
Adventure,Drama,Horror         1
Biography,Comedy,Crime         1
Romance,Sci-Fi                 1
Action,Crime,Sci-Fi            1
Action,Horror,Romance          1
Drama,Romance,War              1
Horror,Mystery,Sci-Fi          1
Animation,Family,Fantasy       1
Biography,Drama,Family         1
Action,Fantasy,War             1
Biography,Drama,Mystery        1
Adventure,Horror,Mystery       1
Adventure,Drama,War            1
Drama,Fantasy,Thriller         1
Comedy,Fantasy,Romance         1
Adventure                      1
Drama,Family,Fantasy           1
Romance,Sci-Fi,Thriller        1
Action,Crime,Sport             1
Drama,Musical,Romance          1
Name: Genre, Length: 207, dtype: int64

In [18]:
genre_groups.filter(lambda x: x['Runtime (Minutes)'].mean() < 120)['Genre'].value_counts()

Drama                         48
Comedy,Drama,Romance          35
Comedy                        32
Drama,Romance                 31
Animation,Adventure,Comedy    27
Comedy,Drama                  27
Action,Adventure,Fantasy      27
Comedy,Romance                26
Crime,Drama,Thriller          24
Crime,Drama,Mystery           23
Action,Crime,Drama            17
Horror,Thriller               16
Drama,Thriller                15
Action,Adventure,Comedy       14
Biography,Drama               14
Action,Crime,Thriller         12
Action,Comedy,Crime           12
Horror                        11
Crime,Drama                   10
Thriller                       9
Action,Thriller                9
Horror,Mystery,Thriller        9
Animation,Action,Adventure     9
Adventure,Comedy,Drama         8
Action,Sci-Fi,Thriller         7
Comedy,Crime,Drama             7
Biography,Comedy,Drama         7
Action,Drama,Thriller          7
Mystery,Thriller               7
Drama,Horror,Thriller          6
                              ..
Animation,Action,Comedy        1
Romance,Sci-Fi,Thriller        1
Action,Fantasy,War             1
Romance,Sci-Fi                 1
Comedy,Fantasy,Romance         1
Comedy,Horror,Sci-Fi           1
Sci-Fi,Thriller                1
Animation,Family,Fantasy       1
Mystery,Romance,Sci-Fi         1
Action,Crime,Fantasy           1
Action,Horror,Romance          1
Action,Comedy,Sci-Fi           1
Thriller,War                   1
Biography,Drama,Family         1
Action,Comedy,Family           1
Adventure,Family               1
Comedy,Sci-Fi                  1
Fantasy,Mystery,Thriller       1
Drama,Romance,War              1
Animation,Comedy,Drama         1
Drama,Horror,Musical           1
Action,Biography,Crime         1
Comedy,Family,Romance          1
Comedy,Music,Romance           1
Comedy,Family,Fantasy          1
Drama,Family,Fantasy           1
Action,Horror                  1
Comedy,Romance,Western         1
Drama,Family                   1
Comedy,Western                 1
Name: Genre, Length: 148, dtype: int64